### ISSUE TITLE
Vagrant fails to start 

### ISSUE THREAD

**Issue by arky** [developish/vagrant-wordpress#3]
$ vagrant up
Invalid gemspec in [/var/lib/gems/1.8/specifications/cucumber-1.0.6.gemspec]: invalid date format in specification: "2011-09-13 00:00:00.000000000Z"
Invalid gemspec in [/var/lib/gems/1.8/specifications/gherkin-2.4.21.gemspec]: invalid date format in specification: "2011-09-16 00:00:00.000000000Z"
Invalid gemspec in [/var/lib/gems/1.8/specifications/json-1.5.4.gemspec]: invalid date format in specification: "2011-08-31 00:00:00.000000000Z"
Invalid gemspec in [/var/lib/gems/1.8/specifications/cucumber-1.0.6.gemspec]: invalid date format in specification: "2011-09-13 00:00:00.000000000Z"
Invalid gemspec in [/var/lib/gems/1.8/specifications/gherkin-2.4.21.gemspec]: invalid date format in specification: "2011-09-16 00:00:00.000000000Z"
Invalid gemspec in [/var/lib/gems/1.8/specifications/json-1.5.4.gemspec]: invalid date format in specification: "2011-08-31 00:00:00.000000000Z"
/var/lib/gems/1.8/gems/vagrant-1.0.1/lib/vagrant/config/vm.rb:44:in `to_s': wrong number of arguments (1 for 0) (ArgumentError)
    from /var/lib/gems/1.8/gems/vagrant-1.0.1/lib/vagrant/config/vm.rb:44:in`forward_port'
    from /home/arky/dev/WP/wp/vagrant-wordpress/Vagrantfile:22
    from /var/lib/gems/1.8/gems/vagrant-1.0.1/lib/vagrant/config/loader.rb:83:in `call'
    from /var/lib/gems/1.8/gems/vagrant-1.0.1/lib/vagrant/config/loader.rb:83:in`load'
    from /var/lib/gems/1.8/gems/vagrant-1.0.1/lib/vagrant/config/loader.rb:79:in `each'
    from /var/lib/gems/1.8/gems/vagrant-1.0.1/lib/vagrant/config/loader.rb:79:in`load'
    from /var/lib/gems/1.8/gems/vagrant-1.0.1/lib/vagrant/config/loader.rb:76:in `each'
    from /var/lib/gems/1.8/gems/vagrant-1.0.1/lib/vagrant/config/loader.rb:76:in`load'
    from /var/lib/gems/1.8/gems/vagrant-1.0.1/lib/vagrant/environment.rb:387:in `load_config!'
    from /var/lib/gems/1.8/gems/vagrant-1.0.1/lib/vagrant/environment.rb:392:in`call'
    from /var/lib/gems/1.8/gems/vagrant-1.0.1/lib/vagrant/environment.rb:392:in `load_config!'
    from /var/lib/gems/1.8/gems/vagrant-1.0.1/lib/vagrant/environment.rb:327:in`load!'
    from /var/lib/gems/1.8/gems/vagrant-1.0.1/bin/vagrant:40
    from /var/lib/gems/1.8/bin/vagrant:19:in `load'
    from /var/lib/gems/1.8/bin/vagrant:19

**Comment by sandnuggah** [comment]
In Vagrantfile, change

`config.vm.forward_port "http",  80,   8080`
`config.vm.forward_port "mysql", 3306, 3306`

to

`config.vm.forward_port  80,   8080`
`config.vm.forward_port 3306, 3306`

**Comment by developish** [comment]
thanks @adamagnaou
